{
 "title": "Storage - PVC/PV",
 "description": "Monitors all persistent volumes that exists within a Kubernetes cluster. Prometheus is used as datasource. ",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "PVC usage statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\"${k8s_namespace}\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} * 100)"
    }
   ]
  },
  { "title": "PVs status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Persistent Volumes",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": " sum by (persistentvolume,storageclass) (kube_persistentvolume_info{namespace=~\"${k8s_namespace}\"})"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Pending|Available|Released|Failed)\"}) by (persistentvolume) + sum(kube_persistentvolume_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Available|Released|Failed)\"}) by (persistentvolume) + sum(kube_persistentvolume_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Released|Failed)\"}) by (persistentvolume) + sum(kube_persistentvolume_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Failed)\"}) by (persistentvolume)"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 11, "y": 13 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  },
  {
   "title": "PV bounded",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "PVs bound" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Bound\"})"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "PVs available" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{ phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "PV pending",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "PVs pending" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{ phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "PV failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "PVs failed" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{ phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "PV released",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "PVs released" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Released\"})"
    }
   ]
  },
  {
   "title": "Allocated volumes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes)/1024/1024/1024"
    }
   ]
  },
  { "title": "Graphical usage data ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Volume allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes)/1024/1024/1024"
    }
   ]
  },
  { "title": "Usage Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Hourly Volume Usage Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1h])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Daily Volume Usage Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Weekly Volume Usage Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1w])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  }
 ]
}